############################################
# DEBUG LOGGING FOR DEVELOPMENT
############################################

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.boot.web.servlet=DEBUG
logging.level.org.springframework.security=DEBUG

# Show SQL queries
logging.level.org.hibernate.SQL=DEBUG

# Show SQL parameters
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Hibernate internal descriptor logs
logging.level.org.hibernate.type.descriptor=TRACE

# Format SQL nicely in logs
spring.jpa.properties.hibernate.format_sql=true

# Print SQL queries in console
spring.jpa.show-sql=true

